# Generated by Django 6.0.2 on 2026-02-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_paymentproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PROOF_SENT', 'Proof Sent'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
